Ac db 2
metravonrech/koa-api-starter pull request #1
Opened 2020-08-10 08:21 UTC by metravonrech

2020-08-10 09:40 UTC, paralectvkomodey commented on README.md
> +Fill data from [google](https://console.developers.google.com/apis/) in `src/config/environment/public.js`
Причина данного изменения?

2020-08-10 09:41 UTC, paralectvkomodey commented on src/resources/user/user.service.js
> +  return _.omit(user);
Не совсем понимаю, зачем это было сделано

2020-08-10 09:41 UTC, paralectvkomodey commented on src/resources/writers/add-book/index.js
> +  genre: Joi.string().pattern(new RegExp(/^(novel|poem)$/)).required(),
Регулярки по своей природе - довольно  медленные. Лучше используй enum для таких целей

2020-08-10 09:41 UTC, paralectvkomodey commented on src/resources/writers/add-book/index.js
> +  title: Joi.string().required(),
У книги должен быть свой уникальный id

2020-08-10 09:46 UTC, paralectvkomodey commented on src/resources/writers/get-writers/index.js
> +  ctx.body = data;
В задании явно указана схема респонса

2020-08-18 07:15 UTC, metravonrech commented on README.md
> +Fill data from [google](https://console.developers.google.com/apis/) in `src/config/environment/public.js`
Уже не помню

2020-08-18 07:15 UTC, metravonrech commented on src/resources/user/user.service.js
> +  return _.omit(user);
Тестил omit, забыл вернуть обратно

2020-08-19 13:41 UTC, paralectvkomodey requested changes

2020-08-19 13:41 UTC, paralectvkomodey commented on src/resources/writers/add-book/index.js
> +    const writer = await writersService.addBook(ctx.request.body);
Отдавать генерацию `id` на откуп клиенту - опасная практика, потому что ты не можешь гарантировать что он это сделает правильно и уникально

Есть два способа генерации уникальных `id` одинакового формата

1. Object ID из MongoDB
2. Используя библиотеки как-то: shortid, uuid, guid и так далее

2020-08-19 13:41 UTC, paralectvkomodey commented on src/resources/writers/add-book/index.js
> +    ctx.statusCode = 418;
Смешно, но давай в 404 всё-таки

2020-08-20 11:03 UTC, metravonrech commented on src/resources/writers/add-book/index.js
> +    const writer = await writersService.addBook(ctx.request.body);
а там в writersService.addBook генерится id книги с помощью uuid

2020-08-24 09:46 UTC, merged